language: node_js
node_js:
- "node"

addons:
  code_climate:
    repo_token: ff794714d59ad950b4def89ac0c2e950692f668361ac0729bc284207f2c39e86

cache:
  yarn: true
  directories:
  - "node_modules"

before_script:
- yarn global add codeclimate-test-reporter

after_script:
- codeclimate-test-reporter < ./coverage/lcov.info
