language: node_js
node_js:
  - "0.12"

addons:
    code_climate:
        repo_token: ff794714d59ad950b4def89ac0c2e950692f668361ac0729bc284207f2c39e86

before_script:
- npm install -g istanbul
- npm install -g mocha
- npm install -g codeclimate-test-reporter

after_script:
  - istanbul cover _mocha -- -R spec ./tests/*.js
  - codeclimate-test-reporter < ./coverage/lcov.info
